---
- name: Download nginx Signing Key 
  ansible.builtin.get_url:
    url: http://nginx.org/keys/nginx_signing.key
    dest: /tmp/
    mode: 0777

- name: Add the signing key
  ansible.builtin.shell:
    cmd: "sudo apt-key add nginx_signing.key && sudo apt update"

- name: Adding APT repository key
  ansible.builtin.apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"
  when: ansible_distribution == 'Ubuntu'

- name: Install the nginx package  on debian
  ansible.builtin.apt:
    name: Nginx
    state: "{{ state }}"
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure dependencies are installed on centos/redhat
  ansible.builtin.yum:
    pkg: epel-release
    state: present
  changed_when: false
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install the nginx package  on centos/redhat
  ansible.builtin.yum:
    name: Nginx
    state: "{{ state }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Ensure nginx service is restarted
  ansible.builtin.service:
    name: Nginx
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for nginx to become ready
  ansible.builtin.wait_for:
    host: "0.0.0.0"
    port: "80"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
