---
- name: Setup group
  ansible.builtin.group:
    name: "{{ nginx_group }}"
    system: true

- name: Setup user
  ansible.builtin.user:
    name: "{{ nginx_user }}"
    system: true
    createhome: false
    group: "{{ nginx_group }}"
