---
# handlers for ansible-role-nginx

- name: Restart nginx
  ansible.builtin.systemd:
    name: Nginx
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: Nginx
    state: reloaded

- name: Start nginx
  ansible.builtin.systemd:
    name: Nginx
    state: started
